from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
DB_PATH = DATA_DIR / "seatalpha.duckdb"

EXCHANGES = ("SHFE", "DCE", "CZCE", "GFEX", "CFFEX")

SYMBOL_META = {
    # Shanghai Futures Exchange / Shanghai International Energy Exchange
    "AD": ("铸造铝合金", "有色", "SHFE"),
    "AG": ("白银", "贵金属", "SHFE"),
    "RB": ("螺纹钢", "黑色", "SHFE"),
    "HC": ("热轧卷板", "黑色", "SHFE"),
    "CU": ("沪铜", "有色", "SHFE"),
    "EC": ("集运指数（欧线）", "航运", "SHFE"),
    "AL": ("沪铝", "有色", "SHFE"),
    "AU": ("黄金", "贵金属", "SHFE"),
    "AO": ("氧化铝", "有色", "SHFE"),
    "BC": ("国际铜", "有色", "SHFE"),
    "BR": ("合成橡胶", "能化", "SHFE"),
    "BU": ("沥青", "能化", "SHFE"),
    "FU": ("燃料油", "能化", "SHFE"),
    "LU": ("低硫燃料油", "能化", "SHFE"),
    "NI": ("沪镍", "有色", "SHFE"),
    "NR": ("20号胶", "能化", "SHFE"),
    "OP": ("胶版印刷纸", "软商品", "SHFE"),
    "PB": ("沪铅", "有色", "SHFE"),
    "RU": ("天然橡胶", "能化", "SHFE"),
    "SC": ("原油", "能化", "SHFE"),
    "SN": ("沪锡", "有色", "SHFE"),
    "SP": ("纸浆", "软商品", "SHFE"),
    "SS": ("不锈钢", "黑色", "SHFE"),
    "WR": ("线材", "黑色", "SHFE"),
    "ZN": ("沪锌", "有色", "SHFE"),
    # Dalian Commodity Exchange
    "A": ("豆一", "油脂油料", "DCE"),
    "B": ("豆二", "油脂油料", "DCE"),
    "BB": ("胶合板", "软商品", "DCE"),
    "BZ": ("纯苯", "能化", "DCE"),
    "C": ("玉米", "农产品", "DCE"),
    "CS": ("玉米淀粉", "农产品", "DCE"),
    "EB": ("苯乙烯", "能化", "DCE"),
    "EG": ("乙二醇", "能化", "DCE"),
    "FB": ("纤维板", "软商品", "DCE"),
    "M": ("豆粕", "油脂油料", "DCE"),
    "I": ("铁矿石", "黑色", "DCE"),
    "P": ("棕榈油", "油脂油料", "DCE"),
    "J": ("焦炭", "黑色", "DCE"),
    "JD": ("鸡蛋", "农产品", "DCE"),
    "JM": ("焦煤", "黑色", "DCE"),
    "L": ("聚乙烯", "能化", "DCE"),
    "LG": ("原木", "软商品", "DCE"),
    "LH": ("生猪", "农产品", "DCE"),
    "LMAF": ("聚乙烯月均价", "能化", "DCE"),
    "PG": ("液化石油气", "能化", "DCE"),
    "PP": ("聚丙烯", "能化", "DCE"),
    "PPMAF": ("聚丙烯月均价", "能化", "DCE"),
    "RR": ("粳米", "农产品", "DCE"),
    "V": ("聚氯乙烯", "能化", "DCE"),
    "VMAF": ("聚氯乙烯月均价", "能化", "DCE"),
    "Y": ("豆油", "油脂油料", "DCE"),
    # Zhengzhou Commodity Exchange
    "AP": ("苹果", "软商品", "CZCE"),
    "MA": ("甲醇", "能化", "CZCE"),
    "SR": ("白糖", "软商品", "CZCE"),
    "CF": ("棉花", "软商品", "CZCE"),
    "CJ": ("红枣", "软商品", "CZCE"),
    "CY": ("棉纱", "软商品", "CZCE"),
    "FG": ("玻璃", "黑色", "CZCE"),
    "JR": ("粳稻", "农产品", "CZCE"),
    "OI": ("菜籽油", "油脂油料", "CZCE"),
    "PF": ("短纤", "能化", "CZCE"),
    "PK": ("花生", "油脂油料", "CZCE"),
    "PL": ("丙烯", "能化", "CZCE"),
    "PM": ("普麦", "农产品", "CZCE"),
    "PR": ("瓶片", "能化", "CZCE"),
    "PX": ("对二甲苯", "能化", "CZCE"),
    "RI": ("早籼稻", "农产品", "CZCE"),
    "RM": ("菜粕", "油脂油料", "CZCE"),
    "RS": ("油菜籽", "油脂油料", "CZCE"),
    "SA": ("纯碱", "能化", "CZCE"),
    "SF": ("硅铁", "黑色", "CZCE"),
    "SH": ("烧碱", "能化", "CZCE"),
    "SM": ("锰硅", "黑色", "CZCE"),
    "TA": ("精对苯二甲酸", "能化", "CZCE"),
    "UR": ("尿素", "能化", "CZCE"),
    "WH": ("强麦", "农产品", "CZCE"),
    "ZC": ("动力煤", "能化", "CZCE"),
    # Guangzhou Futures Exchange
    "SI": ("工业硅", "新能源", "GFEX"),
    "LC": ("碳酸锂", "新能源", "GFEX"),
    "PD": ("钯", "贵金属", "GFEX"),
    "PS": ("多晶硅", "新能源", "GFEX"),
    "PT": ("铂", "贵金属", "GFEX"),
    # China Financial Futures Exchange
    "IC": ("中证500股指", "金融期货", "CFFEX"),
    "IF": ("沪深300股指", "金融期货", "CFFEX"),
    "IH": ("上证50股指", "金融期货", "CFFEX"),
    "IM": ("中证1000股指", "金融期货", "CFFEX"),
    "T": ("10年期国债", "金融期货", "CFFEX"),
    "TF": ("5年期国债", "金融期货", "CFFEX"),
    "TL": ("30年期国债", "金融期货", "CFFEX"),
    "TS": ("2年期国债", "金融期货", "CFFEX"),
}

DEFAULT_SYMBOLS = tuple(SYMBOL_META)
