COPY = {
    "zh": {
        "subtitle": "机构期货持仓全景", "tagline": "外资 · 游资风格 · 机构型席位 · 散户代理席位",
        "update": "更新公开数据", "updating": "正在逐所更新与校验…", "date": "观察日期",
        "sectors": "品种板块", "symbols": "品种", "categories": "席位类别",
        "divergence_only": "只看分歧品种", "consensus_only": "只看三方共振",
        "major_only": "只看今日重大变化", "unclassified": "当前未分类席位",
        "overview": "四类席位总体概览", "overview_note": "同一日期、品种与主力合约口径",
        "sector": "四类席位分类方向速览", "sector_note": "板块内四类席位横向比较",
        "map": "四类席位一致性地图", "map_note": "净仓变化 × 席位一致性；默认展示各板块代表品种",
        "div_map": "核心三方分歧地图", "div_note": "机构信号 × 散户信号；颜色表示外资方向",
        "panorama": "核心品种全景", "panorama_note": "每个品种一行，四类席位并排扫描",
        "changes": "今日关键席位变化", "changes_note": "加多、加空、净仓变化与当前一致性强度前五名",
        "monitor": "分歧监控", "monitor_note": "规则化识别三方同向与反向结构",
        "executive": "要点摘要", "executive_note": "仅基于页面实际数据的确定性摘要",
        "detail": "品种详情", "broker": "席位画像", "status": "数据状态",
        "position_date": "席位数据日期", "price_date": "行情数据日期",
        "no_category": "当前筛选下没有可分类的逐席位明细。", "source": "数据来源",
        "compare": "比较模式", "all": "全部类别", "warning_help": "展开查看并在配置中补充",
        "data_limit": "席位分类是对交易所公布的客户持仓席位进行研究分组；“游资风格”是指定会员席位组合，“散户代理席位”并非个人账户数据，各分类均不代表期货公司自营观点。",
    },
    "en": {
        "subtitle": "Institutional Futures Positioning Atlas", "tagline": "Foreign · Active-trading style · Institution · Retail proxy",
        "update": "Update Public Data", "updating": "Updating and validating each exchange…", "date": "As-of Date",
        "sectors": "Sectors", "symbols": "Instruments", "categories": "Seat Categories",
        "divergence_only": "Divergence only", "consensus_only": "Three-way resonance only",
        "major_only": "Major changes only", "unclassified": "Unclassified seats",
        "overview": "Four-category market overview", "overview_note": "Identical date, instrument and main-contract basis",
        "sector": "Category direction by sector", "sector_note": "Side-by-side category comparison within sectors",
        "map": "Four-category consensus map", "map_note": "Net change × member consensus; sector leaders shown by default",
        "div_map": "Core three-way divergence map", "div_note": "Institution signal × retail signal; color is foreign direction",
        "panorama": "Core instrument panorama", "panorama_note": "One compact row per instrument with four categories",
        "changes": "Key seat changes today", "changes_note": "Top long additions, short additions, net changes and current consensus strength",
        "monitor": "Divergence monitor", "monitor_note": "Rule-based three-way alignment and opposition",
        "executive": "EXECUTIVE READ", "executive_note": "Deterministic summary based only on visible data",
        "detail": "Instrument detail", "broker": "Broker profile", "status": "Data status",
        "position_date": "Position date", "price_date": "Price date",
        "no_category": "No classifiable member-level detail matches the current filters.", "source": "Sources",
        "compare": "Compare mode", "all": "All categories", "warning_help": "Expand and add them to the configuration",
        "data_limit": "Categories group exchange-published client-position seats. Active-trading style is a named member basket; retail proxy is not personal-account data. No category represents a futures-company house view.",
    },
}


def cp(lang: str, key: str) -> str:
    return COPY.get(lang, COPY["zh"]).get(key, key)
